---

_You are currently looking at **version 1.5** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-data-analysis/resources/0dhYG) course resource._

---

# Assignment 3 - More Pandas
This assignment requires more individual learning then the last one did - you are encouraged to check out the [pandas documentation](http://pandas.pydata.org/pandas-docs/stable/) to find functions or methods you might not have used yet, or ask questions on [Stack Overflow](http://stackoverflow.com/) and tag them as pandas and python related. And of course, the discussion forums are open for interaction with your peers and the course staff.

### Question 1 (20%)
Load the energy data from the file `Energy Indicators.xls`, which is a list of indicators of [energy supply and renewable electricity production](Energy%20Indicators.xls) from the [United Nations](http://unstats.un.org/unsd/environment/excel_file_tables/2013/Energy%20Indicators.xls) for the year 2013, and should be put into a DataFrame with the variable name of **energy**.

Keep in mind that this is an Excel file, and not a comma separated values file. Also, make sure to exclude the footer and header information from the datafile. The first two columns are unneccessary, so you should get rid of them, and you should change the column labels so that the columns are:

`['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']`

Convert `Energy Supply` to gigajoules (there are 1,000,000 gigajoules in a petajoule). For all countries which have missing data (e.g. data with "...") make sure this is reflected as `np.NaN` values.

Rename the following list of countries (for use in later questions):

```"Republic of Korea": "South Korea",
"United States of America": "United States",
"United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
"China, Hong Kong Special Administrative Region": "Hong Kong"```

There are also several countries with numbers and/or parenthesis in their name. Be sure to remove these, 

e.g. 

`'Bolivia (Plurinational State of)'` should be `'Bolivia'`, 

`'Switzerland17'` should be `'Switzerland'`.

<br>

Next, load the GDP data from the file `world_bank.csv`, which is a csv containing countries' GDP from 1960 to 2015 from [World Bank](http://data.worldbank.org/indicator/NY.GDP.MKTP.CD). Call this DataFrame **GDP**. 

Make sure to skip the header, and rename the following list of countries:

```"Korea, Rep.": "South Korea", 
"Iran, Islamic Rep.": "Iran",
"Hong Kong SAR, China": "Hong Kong"```

<br>

Finally, load the [Sciamgo Journal and Country Rank data for Energy Engineering and Power Technology](http://www.scimagojr.com/countryrank.php?category=2102) from the file `scimagojr-3.xlsx`, which ranks countries based on their journal contributions in the aforementioned area. Call this DataFrame **ScimEn**.

Join the three datasets: GDP, Energy, and ScimEn into a new dataset (using the intersection of country names). Use only the last 10 years (2006-2015) of GDP data and only the top 15 countries by Scimagojr 'Rank' (Rank 1 through 15). 

The index of this DataFrame should be the name of the country, and the columns should be ['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations',
       'Citations per document', 'H index', 'Energy Supply',
       'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015'].

*This function should return a DataFrame with 20 columns and 15 entries.*

In [2]:
def answer_one():
    from functools import reduce
    import pandas as pd
    import numpy as np
    energy = pd.read_excel("Energy Indicators.xls",skiprows=17,skip_footer=38)
    energy = energy[['Unnamed: 1','Petajoules','Gigajoules','%']]
    energy.columns= ['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']
    energy['Energy Supply']=energy['Energy Supply']*1000000
    energy['Country']= energy['Country'].replace({"Republic of Korea": "South Korea","United States of America": "United States","United Kingdom of Great Britain and Northern Ireland" : "United Kingdom","China, Hong Kong Special Administrative Region": "Hong Kong"})
    energy['Country'] = energy['Country'].str.replace(".","")
    
    GDP=pd.read_csv("world_bank.csv",skiprows=4)
    GDP["Country Name"]=GDP["Country Name"].replace({"Korea, Rep.": "South Korea","Iran, Islamic Rep.": "Iran","Hong Kong SAR, China": "Hong Kong"})
    GDP=GDP[['Country Name','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015']]
    GDP.columns=['Country','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015']
    
    ScimEn=pd.read_excel("scimagojr-3.xlsx")
    ScimEn=ScimEn[:15]
    
    df = pd.merge(ScimEn,energy,how='outer',left_on='Country',right_on='Country')
    final_df = pd.merge(df,GDP,how='inner',left_on='Country',right_on='Country')
    final_df = final_df.set_index('Country')
    #final_df = final_df[0:15]
    return final_df
answer_one()

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
China,1.0,127050.0,126767.0,597237.0,411683.0,4.70,138.0,127191000000,93,19.754910,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
United States,2.0,96661.0,94747.0,792274.0,265436.0,8.20,230.0,90838000000,286,11.570980,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
Japan,3.0,30504.0,30287.0,223024.0,61554.0,7.31,134.0,18984000000,149,10.232820,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
United Kingdom,4.0,20944.0,20357.0,206091.0,37874.0,9.84,139.0,7920000000,124,10.600470,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12
Russian Federation,5.0,18534.0,18301.0,34266.0,12422.0,1.85,57.0,30709000000,214,17.288680,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12
Canada,6.0,17899.0,17620.0,215003.0,40930.0,12.01,149.0,10431000000,296,61.945430,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12
Germany,7.0,17027.0,16831.0,140566.0,27426.0,8.26,126.0,13261000000,165,17.901530,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12
India,8.0,15005.0,14841.0,128763.0,37209.0,8.58,115.0,33195000000,26,14.969080,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12
France,9.0,13153.0,12973.0,130632.0,28601.0,9.93,114.0,10597000000,166,17.020280,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12
South Korea,10.0,11983.0,11923.0,114675.0,22595.0,9.57,104.0,11007000000,221,2.279353,9.410199e+11,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12
Italy,11.0,10964.0,10794.0,111850.0,26661.0,10.20,106.0,6530000000,109,33.667230,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12
Spain,12.0,9428.0,9330.0,123336.0,23964.0,13.08,115.0,4923000000,106,37.968590,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12
Iran,13.0,8896.0,8819.0,57470.0,19125.0,6.46,72.0,NaN,NaN,NaN,3.895523e+11,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN
Australia,14.0,8831.0,8725.0,90765.0,15606.0,10.28,107.0,5386000000,231,11.810810,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
Brazil,15.0,8668.0,8596.0,60702.0,14396.0,7.00,86.0,12149000000,59,69.648030,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12
Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,321000000,10,78.669280,1.030523e+10,1.172119e+10,1.214448e+10,1.469733e+10,1.593680e+10,1.691113e+10,1.935220e+10,1.973134e+10,1.999032e+10,2.029415e+10
Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102000000,35,100.000000,9.771760e+09,1.034829e+10,1.112752e+10,1.150029e+10,1.192695e+10,1.223109e+10,1.240477e+10,1.254247e+10,1.279331e+10,1.312082e+10
Algeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1959000000,51,0.551010,1.446474e+11,1.495654e+11,1.531550e+11,1.556055e+11,1.612073e+11,1.658823e+11,1.715223e+11,1.763249e+11,1.830252e+11,1.901632e+11
American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,.................................................,...,0.641026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9000000,121,88.695650,4.018196e+09,4.021331e+09,3.675728e+09,3.535389e+09,3.346317e+09,3.185605e+09,3.129538e+09,3.127550e+09,NaN,NaN
Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,642000000,27,70.909090,5.581103e+10,6.842044e+10,7.787420e+10,7.975320e+10,8.247091e+10,8.570262e+10,9.012096e+10,9.626143e+10,1.008863e+11,1.039106e+11
Antigua and Barbuda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8000000,84,0.000000,1.268714e+09,1.389229e+09,1.390217e+09,1.222890e+09,1.135539e+09,1.115174e+09,1.159999e+09,1.155982e+09,1.211723e+09,1.256122e+09
Argentina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3378000000,79,24.064520,3.788140e+11,4.089887e+11,4.215649e+11,4.217758e+11,4.616402e+11,5.003555e+11,5.043671e+11,5.189199e+11,5.212737e+11,NaN
Armenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,143000000,48,28.236060,8.679746e+09,9.873142e+09,1.055439e+10,9.060944e+09,9.260285e+09,9.695518e+09,1.039360e+10,1.073658e+10,1.111236e+10,1.144574e+10
Aruba,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12000000,120,14.870690,NaN,NaN,NaN,NaN,2.467704e+09,NaN,NaN,NaN,NaN,NaN
Austria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1391000000,164,72.452820,3.782096e+11,3.919065e+11,3.979703e+11,3.828512e+11,3.902351e+11,4.011929e+11,4.042312e+11,4.055298e+11,4.069632e+11,4.104717e+11
Azerbaijan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,567000000,60,6.384345,3.329047e+10,4.162940e+10,4.611390e+10,5.045352e+10,5.290270e+10,5.293758e+10,5.410221e+10,5.723834e+10,5.838310e+10,5.902532e+10
Bahrain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,574000000,425,0.000000,2.088961e+10,2.262186e+10,2.403463e+10,2.464505e+10,2.571327e+10,2.625330e+10,2.719545e+10,2.866752e+10,2.995210e+10,3.082866e+10
Bangladesh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1625000000,10,1.966329,9.158885e+10,9.805377e+10,1.039505e+11,1.091950e+11,1.152791e+11,1.227312e+11,1.307350e+11,1.385969e+11,1.469974e+11,1.566295e+11
Barbados,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19000000,69,0.000000,4.522426e+09,4.599352e+09,4.619595e+09,4.433354e+09,4.445500e+09,4.477890e+09,4.490036e+09,4.490036e+09,4.498133e+09,4.542669e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Solomon Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6000000,11,0.000000,5.737567e+08,6.157557e+08,6.594405e+08,6.282630e+08,6.715852e+08,7.584110e+08,7.937576e+08,8.176845e+08,8.300105e+08,8.570189e+08
Somalia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,126000000,12,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
South Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6341000000,119,1.687019,3.402852e+11,3.585261e+11,3.699668e+11,3.642764e+11,3.753494e+11,3.874074e+11,3.960071e+11,4.047682e+11,4.110369e+11,4.163117e+11
South Sudan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28000000,2,0.423729,NaN,NaN,1.419283e+10,1.490838e+10,1.572736e+10,1.499756e+10,8.086368e+09,9.148087e+09,9.456711e+09,8.856231e+09
Sri Lanka,NaN,NaN,NaN,NaN,NaN,NaN,NaN,388000000,19,59.573230,4.482590e+10,4.787264e+10,5.072110e+10,5.251608e+10,5.672575e+10,6.149340e+10,6.711671e+10,6.939580e+10,7.278134e+10,7.626465e+10
Sudan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,608000000,16,78.410480,5.110640e+10,5.699483e+10,6.144155e+10,6.343339e+10,6.563411e+10,6.434261e+10,6.291761e+10,6.499389e+10,6.700870e+10,6.931354e+10
Suriname,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34000000,65,22.023810,3.683884e+09,3.872186e+09,4.032626e+09,4.154157e+09,4.368398e+09,4.598491e+09,4.739717e+09,4.874218e+09,4.964045e+09,5.038473e+09
Swaziland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49000000,39,40.677970,3.233868e+09,3.347171e+09,3.426617e+09,3.469462e+09,3.527777e+09,3.574597e+09,3.682817e+09,3.791429e+09,3.884333e+09,3.948711e+09
Sweden,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2044000000,212,46.598460,4.726099e+11,4.887020e+11,4.859797e+11,4.607834e+11,4.883793e+11,5.013917e+11,4.999562e+11,5.061616e+11,5.176362e+11,5.388264e+11
Switzerland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1113000000,136,57.745480,5.415550e+11,5.639773e+11,5.768204e+11,5.645363e+11,5.812117e+11,5.917000e+11,5.983544e+11,6.089383e+11,6.204440e+11,6.260878e+11
Syrian Arab Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,542000000,28,11.568270,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Tajikistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,106000000,13,99.742920,4.387963e+09,4.730224e+09,5.103912e+09,5.297861e+09,5.642222e+09,6.059746e+09,6.514227e+09,6.996280e+09,7.464978e+09,7.778507e+09
Thailand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5336000000,79,4.305189,2.978681e+11,3.140575e+11,3.194770e+11,3.171184e+11,3.409236e+11,3.437658e+11,3.686234e+11,3.785840e+11,3.816794e+11,3.924416e+11
Timor-Leste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7000000,6,0.000000,5.940000e+08,6.620000e+08,7.560000e+08,8.540000e+08,9.340000e+08,1.023000e+09,1.088000e+09,1.118000e+09,1.179490e+09,1.229630e+09
Togo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,134000000,19,80.180180,2.818834e+09,2.883398e+09,2.947568e+09,3.051036e+09,3.172946e+09,3.327905e+09,3.488321e+09,3.626731e+09,3.842067e+09,4.052431e+09
Tonga,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3000000,28,0.000000,3.591646e+08,3.427468e+08,3.511655e+08,3.550268e+08,3.698161e+08,3.772832e+08,3.793467e+08,3.691972e+08,3.771126e+08,NaN
Trinidad and Tobago,NaN,NaN,NaN,NaN,NaN,NaN,NaN,824000000,611,0.000000,2.033516e+10,2.130193e+10,2.202416e+10,2.105717e+10,2.103761e+10,2.103908e+10,2.132649e+10,2.169752e+10,2.187468e+10,2.209480e+10
Tunisia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,430000000,39,3.492547,3.712967e+10,3.962093e+10,4.129998e+10,4.255692e+10,4.405093e+10,4.300079e+10,4.459182e+10,4.561743e+10,4.666663e+10,4.703997e+10
Turkey,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4897000000,64,28.536690,6.680034e+11,6.991896e+11,7.037962e+11,6.698319e+11,7.311681e+11,7.953116e+11,8.122315e+11,8.462844e+11,8.718432e+11,9.065849e+11
Turkmenistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1102000000,210,0.000000,1.530130e+10,1.699352e+10,1.949156e+10,2.068055e+10,2.258316e+10,2.590288e+10,2.877810e+10,3.171347e+10,3.497996e+10,3.725365e+10
Turks and Caicos Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3000000,85,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Tuvalu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,.................................................,...,0.000000,2.980999e+07,3.170309e+07,3.423404e+07,3.271649e+07,3.182352e+07,3.451366e+07,3.457388e+07,3.502271e+07,3.571892e+07,NaN
Uganda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,452000000,12,68.018180,1.518174e+10,1.645889e+10,1.789225e+10,1.918963e+10,2.018180e+10,2.213403e+10,2.311042e+10,2.386630e+10,2.501553e+10,2.627705e+10
Ukraine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4844000000,107,8.067312,1.392103e+11,1.502079e+11,1.536627e+11,1.309206e+11,1.364193e+11,1.435131e+11,1.438001e+11,1.438001e+11,1.343093e+11,1.210127e+11
United Arab Emirates,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2710000000,300,0.000000,2.789489e+11,2.878318e+11,2.970189e+11,2.814464e+11,2.860493e+11,3.009462e+11,3.216922e+11,3.355937e+11,3.509313e+11,3.621003e+11
Uruguay,NaN,NaN,NaN,NaN,NaN,NaN,NaN,196000000,58,71.605040,3.139363e+10,3.344725e+10,3.584747e+10,3.736865e+10,4.028468e+10,4.236423e+10,4.386315e+10,4.589732e+10,4.738384e+10,4.784927e+10
Uzbekistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1798000000,62,21.328410,2.798925e+10,3.076611e+10,3.353506e+10,3.625140e+10,3.933277e+10,4.259739e+10,4.609038e+10,4.977761e+10,5.380959e+10,5.811436e+10
Vanuatu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3000000,10,14.705880,5.961693e+08,6.270251e+08,6.674589e+08,6.895706e+08,7.008043e+08,7.093767e+08,7.218245e+08,7.360383e+08,7.529991e+08,NaN
Zambia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,400000000,26,99.714670,1.440569e+10,1.560892e+10,1.682234e+10,1.837342e+10,2.026555e+10,2.140358e+10,2.302438e+10,2.420595e+10,2.542227e+10,2.624127e+10
Zimbabwe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,480000000,32,52.536120,1.006276e+10,9.695130e+09,7.982103e+09,8.459783e+09,9.422161e+09,1.054391e+10,1.165789e+10,1.218064e+10,1.264939e+10,1.278517e+10

### Question 2 (6.6%)
The previous question joined three datasets then reduced this to just the top 15 entries. When you joined the datasets, but before you reduced this to the top 15 items, how many entries did you lose?

*This function should return a single number.*

In [ ]:
%%HTML
<svg width="800" height="300">
  <circle cx="150" cy="180" r="80" fill-opacity="0.2" stroke="black" stroke-width="2" fill="blue" />
  <circle cx="200" cy="100" r="80" fill-opacity="0.2" stroke="black" stroke-width="2" fill="red" />
  <circle cx="100" cy="100" r="80" fill-opacity="0.2" stroke="black" stroke-width="2" fill="green" />
  <line x1="150" y1="125" x2="300" y2="150" stroke="black" stroke-width="2" fill="black" stroke-dasharray="5,3"/>
  <text  x="300" y="165" font-family="Verdana" font-size="35">Everything but this!</text>
</svg>

In [ ]:
def answer_two():
    import pandas as pd
    import numpy as np
    energy = pd.read_excel('Energy Indicators.xls', skip_footer=38, skiprows=17, parse_cols='C:F')
    col_names = ['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']
    energy.columns = col_names
    energy.loc[energy['Energy Supply'] == '...'] = np.NaN
    energy[['Energy Supply', 'Energy Supply per Capita']] = energy[['Energy Supply', 'Energy Supply per Capita']].apply(pd.to_numeric)
    energy['Energy Supply'] = energy['Energy Supply']*10**6
    energy['Country'] = energy['Country'].str.replace(r" \(.*\)","")
    energy['Country'] = energy['Country'].str.replace(r"([0-9]+)$","")
    replace_dict={"Republic of Korea": "South Korea","United States of America": "United States","United Kingdom of Great Britain and Northern Ireland": "United Kingdom","China, Hong Kong Special Administrative Region": "Hong Kong"}
    energy['Country'].replace(to_replace=replace_dict, inplace=True)
    energy.reset_index()
    energy = energy.set_index('Country')
    en_shape = energy.shape
    
    GDP = pd.read_csv('world_bank.csv', skiprows=4)
    replace_dict = {"Korea, Rep.": "South Korea", "Iran, Islamic Rep.": "Iran","Hong Kong SAR, China": "Hong Kong"}
    GDP['Country Name'].replace(to_replace=replace_dict, inplace=True)
    years_to_keep = np.arange(2006, 2016).astype(str)
    GDP = GDP[np.append(['Country Name'],years_to_keep)]
    GDP.reset_index()
    GDP = GDP.rename(columns={'Country Name': 'Country'})
    GDP = GDP.set_index('Country')
    GDP_shape = GDP.shape
    
    ScimEn = pd.read_excel('scimagojr-3.xlsx', header=0)
    ScimEn.reset_index()
    ScimEn = ScimEn.set_index('Country')
    ScimEn_shape = ScimEn.shape
    
    first_merge = pd.merge(energy, GDP, how='outer', left_index=True, right_index=True)
    result = pd.merge(ScimEn, first_merge, how='outer', left_index=True, right_index=True)
    #result = result.reset_index().dropna(thresh=result.shape[1]-10).set_index('Country')
    result = result.shape[0]-15
    
    return result

answer_two()

## Answer the following questions in the context of only the top 15 countries by Scimagojr Rank (aka the DataFrame returned by `answer_one()`)

### Question 3 (6.6%)
What is the average GDP over the last 10 years for each country? (exclude missing values from this calculation.)

*This function should return a Series named `avgGDP` with 15 countries and their average GDP sorted in descending order.*

In [ ]:
def answer_three():
    Top15 = answer_one()
    Top15 = Top15[['2006','2007','2008','2009','2010','2011','2012','2013','2014','2015']]
    avgGDP= Top15.mean(axis=1,skipna=True).sort_values(ascending=False)
    return avgGDP
#answer_three()

### Question 4 (6.6%)
By how much had the GDP changed over the 10 year span for the country with the 6th largest average GDP?

*This function should return a single number.*

In [ ]:
def answer_four():
    Top15 = answer_one()
    change= Top15[Top15['Rank']==4]['2015']-Top15[Top15['Rank']==4]['2006']
    return change[0]
answer_four()

### Question 5 (6.6%)
What is the mean `Energy Supply per Capita`?

*This function should return a single number.*

In [ ]:
def answer_five():
    import numpy as np
    Top15 = answer_one()
    result = Top15['Energy Supply per Capita'].mean(axis=0)
    return result

answer_five()

### Question 6 (6.6%)
What country has the maximum % Renewable and what is the percentage?

*This function should return a tuple with the name of the country and the percentage.*

In [ ]:
def answer_six():
    Top15 = answer_one()
    ans= Top15[Top15['% Renewable']== Top15['% Renewable'].max()]
    return (ans.index.tolist()[0],ans['% Renewable'].tolist()[0])
answer_six()

### Question 7 (6.6%)
Create a new column that is the ratio of Self-Citations to Total Citations. 
What is the maximum value for this new column, and what country has the highest ratio?

*This function should return a tuple with the name of the country and the ratio.*

In [ ]:
def answer_seven():
    Top15 = answer_one()
    Top15['Ratio']=Top15['Self-citations']/Top15['Citations']
    max= Top15[Top15['Ratio']==Top15['Ratio'].max()]
    return (max.index.tolist()[0],max['Ratio'].tolist()[0])
answer_seven()

### Question 8 (6.6%)

Create a column that estimates the population using Energy Supply and Energy Supply per capita. 
What is the third most populous country according to this estimate?

*This function should return a single string value.*

In [ ]:
def answer_eight():
    Top15 = answer_one()
    Top15['Population Est.'] = Top15['Energy Supply']/Top15['Energy Supply per Capita']
    thirdpop = Top15['Population Est.'].sort_values(ascending=False)
    val = thirdpop[2]
    val=Top15[Top15['Population Est.']==val]
    return val.index.tolist()[0]

answer_eight()

### Question 9 (6.6%)
Create a column that estimates the number of citable documents per person. 
What is the correlation between the number of citable documents per capita and the energy supply per capita? Use the `.corr()` method, (Pearson's correlation).

*This function should return a single number.*

*(Optional: Use the built-in function `plot9()` to visualize the relationship between Energy Supply per Capita vs. Citable docs per Capita)*

In [3]:
import pandas as pd
def answer_nine():
    import numpy as np
    Top15 = answer_one()
    Top15['PopEst'] = Top15['Energy Supply']/Top15['Energy Supply per Capita']
    Top15['Citable docs per Person'] = Top15['Citable documents']/Top15['PopEst']
    Top15['Citable docs per Person']=pd.to_numeric(Top15['Citable docs per Person'])
    Top15['Energy Supply per Capita']=pd.to_numeric(Top15['Energy Supply per Capita'])
    res= Top15['Citable docs per Person'].corr(Top15['Energy Supply per Capita'],method='pearson')
    return res
answer_nine()

0.79019354883008763

In [ ]:
def plot9():
    import matplotlib as plt
    %matplotlib inline
    
    Top15 = answer_one()
    Top15['PopEst'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    Top15['Citable docs per Capita'] = Top15['Citable documents'] / Top15['PopEst']
    Top15.plot(x='Citable docs per Capita', y='Energy Supply per Capita', kind='scatter', xlim=[0, 0.0006])
#plot9()

In [ ]:
#plot9()

### Question 10 (6.6%)
Create a new column with a 1 if the country's % Renewable value is at or above the median for all countries in the top 15, and a 0 if the country's % Renewable value is below the median.

*This function should return a series named `HighRenew` whose index is the country name sorted in ascending order of rank.*

In [4]:
def answer_ten():
    import numpy as np
    Top15 = answer_one()
    Top15['median % Renewable'] = Top15['% Renewable'].median()
    Top15['HighRenew'] = Top15['% Renewable'] >= Top15['median % Renewable']
    return Top15['HighRenew'].sort_values(ascending=True)

answer_ten()

Country
United States         False
Japan                 False
United Kingdom        False
India                 False
France                False
South Korea           False
Iran                  False
Australia             False
China                  True
Russian Federation     True
Canada                 True
Germany                True
Italy                  True
Spain                  True
Brazil                 True
Name: HighRenew, dtype: bool

### Question 11 (6.6%)
Use the following dictionary to group the Countries by Continent, then create a dateframe that displays the sample size (the number of countries in each continent bin), and the sum, mean, and std deviation for the estimated population of each country.

```python
ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}
```

*This function should return a DataFrame with index named Continent `['Asia', 'Australia', 'Europe', 'North America', 'South America']` and columns `['size', 'sum', 'mean', 'std']`*

In [ ]:
def answer_eleven():
    import numpy as np
    import pandas as pd
    Top15 = answer_one()
    ContinentDict  = {'China':'Asia',
                      'United States':'North America', 
                      'Japan':'Asia',
                      'United Kingdom':'Europe',
                      'Russian Federation':'Europe',
                      'Canada':'North America',
                      'Germany':'Europe', 
                      'India':'Asia',
                      'France':'Europe', 
                      'South Korea':'Asia', 
                      'Italy':'Europe', 
                      'Spain':'Europe', 
                      'Iran':'Asia',
                      'Australia':'Australia', 
                      'Brazil':'South America'}
    Top15 = Top15.reset_index()
    Top15['Continent'] = Top15['Country'].map(ContinentDict)
    Top15['PopEst'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    result = Top15.copy()
    result = result[['Continent', 'PopEst']]
    result = result.groupby('Continent')['PopEst'].agg({'size': np.size,'sum': np.sum,'mean': np.mean,'std': np.std})
    #result = grouped.agg(['np.size', 'sum', 'mean', 'std'])
    idx = pd.IndexSlice
    #result = result.loc[:, idx['PopEst']]
    #result = result.reset_index()
    #result = result.set_index('Continent')
    return result

#answer_eleven()

### Question 12 (6.6%)
Cut % Renewable into 5 bins. Group Top15 by the Continent, as well as these new % Renewable bins. How many countries are in each of these groups?

*This function should return a __Series__ with a MultiIndex of `Continent`, then the bins for `% Renewable`. Do not include groups with no countries.*

In [ ]:
def answer_twelve():
    import numpy as np
    import pandas as pd
    Top15 = answer_one()
    ContinentDict  = {'China':'Asia',
                      'United States':'North America', 
                      'Japan':'Asia',
                      'United Kingdom':'Europe',
                      'Russian Federation':'Europe',
                      'Canada':'North America',
                      'Germany':'Europe', 
                      'India':'Asia',
                      'France':'Europe', 
                      'South Korea':'Asia', 
                      'Italy':'Europe', 
                      'Spain':'Europe', 
                      'Iran':'Asia',
                      'Australia':'Australia', 
                      'Brazil':'South America'}
    Top15 = Top15.reset_index()
    Top15['Continent'] = Top15['Country'].map(ContinentDict)
    Top15['% Renewable'] = pd.cut(Top15['% Renewable'], 5)
    result = Top15.groupby(['Continent', '% Renewable'])['Country'].count()
    result = result.reset_index()
    #result.drop('Country', axis=1, inplace=True)
    
    result = result.set_index(['Continent', '% Renewable'])
    return result['Country']

#answer_twelve()

### Question 13 (6.6%)
Convert the Population Estimate series to a string with thousands separator (using commas). Do not round the results.

e.g. 317615384.61538464 -> 317,615,384.61538464

*This function should return a Series `PopEst` whose index is the country name and whose values are the population estimate string.*

In [ ]:
def answer_thirteen():
    import numpy as np
    Top15 = answer_one()
    Top15['PopEst'] = Top15['Energy Supply']/Top15['Energy Supply per Capita']
    Top15['PopEst'] = Top15['PopEst'].apply('{:,}'.format)
    return Top15['PopEst']

#answer_thirteen()

### Optional

Use the built in function `plot_optional()` to see an example visualization.

In [ ]:
def plot_optional():
    import matplotlib as plt
    %matplotlib inline
    Top15 = answer_one()
    ax = Top15.plot(x='Rank', y='% Renewable', kind='scatter', 
                    c=['#e41a1c','#377eb8','#e41a1c','#4daf4a','#4daf4a','#377eb8','#4daf4a','#e41a1c',
                       '#4daf4a','#e41a1c','#4daf4a','#4daf4a','#e41a1c','#dede00','#ff7f00'], 
                    xticks=range(1,16), s=6*Top15['2014']/10**10, alpha=.75, figsize=[16,6]);

    for i, txt in enumerate(Top15.index):
        ax.annotate(txt, [Top15['Rank'][i], Top15['% Renewable'][i]], ha='center')

    print("This is an example of a visualization that can be created to help understand the data. \
This is a bubble chart showing % Renewable vs. Rank. The size of the bubble corresponds to the countries' \
2014 GDP, and the color corresponds to the continent.")
#plot_optional

In [ ]:
#plot_optional() # Be sure to comment out plot_optional() before submitting the assignment!